services:
  amazon-q:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${AMAZON_Q_WORKSPACE:-${AMAZON_Q_DEFAULT_WORKSPACE}}:/home/developer/workspace:cached
      - ~/.aws/nskp_config/netskope-cert-bundle.pem:/home/developer/.aws/nskp_config/netskope-cert-bundle.pem:cached
      - ./amazonq:/home/developer/.config/amazonq:cached
      - ./.vscode:/vscode:cached
    env_file:
      - .env
    command: sleep infinity
    user: developer
