name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build DevContainer
      run: |
        docker build -f .devcontainer/Dockerfile -t amazon-q-devcontainer .
    
    - name: Run Integration Tests
      run: |
        docker run --rm -v $PWD:/workspace amazon-q-devcontainer /workspace/tests/integration-test.sh
    
    - name: Security Scan
      run: |
        docker run --rm -v $PWD:/workspace amazon-q-devcontainer /workspace/scripts/security-check.sh

  build-multiarch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build for ${{ matrix.platform }}
      run: |
        docker buildx build --platform ${{ matrix.platform }} -f .devcontainer/Dockerfile .
